application: search-gonuts-io
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
  mime_type: text/plain
- url: .*
  script: main.app
