application: search-gonuts-io
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
- url: /apple-touch-icon(.*)\.png
  static_files: public/apple-touch-icon\1.png
  upload: public/apple-touch-icon(.*).png

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  mime_type: text/plain

- url: /add
  script: search.add
- url: /remove
  script: search.remove
- url: /
  script: search.find
